import Head from 'next/head'
import Image from 'next/image'
import IntroMenu from '../components/introMenu'
import ProductCard from '../components/productCard'
import styles from '../styles/Home.module.css'


export default function HomePage({ products }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <IntroMenu />
        <div id='about' className={styles.section}>
          <h2 className={styles.sectionTitle}>About</h2>
          <div className={styles.sectionContent}>
            <Image style={{ borderRadius: '50%', overflow: 'hidden' }} src="/images/profile-test.jpg" alt="Test profile" width={200} height={200} />
          </div>
          <div className={styles.sectionContent}>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris imperdiet sem ac orci varius ullamcorper. Duis tincidunt viverra tincidunt. Fusce dignissim a nisl a tempus. In imperdiet elementum sem, eu faucibus enim pretium in. Suspendisse a lobortis nibh. Aliquam magna nibh, malesuada sed ligula eget, sollicitudin posuere velit. Integer hendrerit est a efficitur blandit.
            </p>
          </div>
        </div>

        <div className={styles.saleBanner}>
          <h2>SHOP CHRISTMAS SALE NOW!</h2>
        </div>

        <div id='shop' className={styles.section}>
          {products && products.map((product: any) => (
            <ProductCard _id={product._id} name={product.name} price={product.price} details={product.details} picLink={product.picLink} />
          ))}
          {/* <ProductCard name={'Test name'} price={4.99} picLink={''}/>
          <ProductCard name={'Test name'} price={4.99} picLink={''}/>
          <ProductCard name={'Test name'} price={4.99} picLink={''}/> */}
        </div>

        <div id='giving' className={styles.section}>
          <div className={styles.sectionContentVert}>
            <h2>Where we're giving to</h2>
            <div className={styles.sectionContent}>
              <div className={styles.sectionContent}>
                <Image src="/images/profile-test.jpg" alt="Test profile" width={200} height={200} />
              </div>
              <div className={styles.sectionContent}>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris imperdiet sem ac orci varius ullamcorper. Duis tincidunt viverra tincidunt. Fusce dignissim a nisl a tempus. In imperdiet elementum sem, eu faucibus enim pretium in. Suspendisse a lobortis nibh. Aliquam magna nibh, malesuada sed ligula eget, sollicitudin posuere velit. Integer hendrerit est a efficitur blandit.
                </p>
              </div> 
            </div>
          </div>
        </div>

        <div id='contact' className={styles.section}>
          <h2 className={styles.sectionTitle}>Get in touch</h2>
          <div className={styles.sectionContent}>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris imperdiet sem ac orci varius ullamcorper. Duis tincidunt viverra tincidunt. Fusce dignissim a nisl a tempus. In imperdiet elementum sem, eu faucibus enim pretium in. Suspendisse a lobortis nibh. Aliquam magna nibh, malesuada sed ligula eget, sollicitudin posuere velit. Integer hendrerit est a efficitur blandit.
            </p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
