import Head from 'next/head'
import Image from 'next/image'
import IntroMenu from '../components/introMenu'
import ProductCard from '../components/productCard'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const res = await fetch('http://localhost:8080/products');
  const productsJson = await res.json();
  console.log(productsJson);
  return {
    props: {
      products: productsJson
    }
  };
}

export default function Home({ products }) {
  // console.log(products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <div className={styles.banner}>
          <h1 className={styles.title}>
            Clarigraphy
          </h1>
        </div>

        <div className={styles.navBar}>
          <a href="https://nextjs.org/docs" className={styles.navBarButton}>About</a>
          <a href="https://nextjs.org/docs" className={styles.navBarButton}>Shop</a>
          <a href="https://nextjs.org/docs" className={styles.navBarButton}>Giving - Christmas Donations</a>
          <a href="https://nextjs.org/docs" className={styles.navBarButton}>Get in touch</a>
        </div> */}
        <IntroMenu />

        <div className={styles.section}>
          <h2 className={styles.sectionTitle}>About</h2>
          <div className={styles.sectionContent}>
            <Image style={{ borderRadius: '50%', overflow: 'hidden' }} src="/images/profile-test.jpg" alt="Test profile" width={200} height={200} />
          </div>
          <div className={styles.sectionContent}>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris imperdiet sem ac orci varius ullamcorper. Duis tincidunt viverra tincidunt. Fusce dignissim a nisl a tempus. In imperdiet elementum sem, eu faucibus enim pretium in. Suspendisse a lobortis nibh. Aliquam magna nibh, malesuada sed ligula eget, sollicitudin posuere velit. Integer hendrerit est a efficitur blandit.
            </p>
          </div>
        </div>

        <div className={styles.saleBanner}>
          <h2>SHOP CHRISTMAS SALE NOW!</h2>
        </div>

        <div className={styles.section}>
          {products.map((product) => (
            <ProductCard name={product.name} price={product.price} picLink={product.picLink}/>
          ))}
          {/* <ProductCard name={'Test name'} price={4.99} picLink={''}/>
          <ProductCard name={'Test name'} price={4.99} picLink={''}/>
          <ProductCard name={'Test name'} price={4.99} picLink={''}/> */}
        </div>

        <div className={styles.section}>
          <div className={styles.sectionContentVert}>
            <h2>Where we're giving to</h2>
            <div className={styles.sectionContent}>
              <div className={styles.sectionContent}>
                <Image src="/images/profile-test.jpg" alt="Test profile" width={200} height={200} />
              </div>
              <div className={styles.sectionContent}>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris imperdiet sem ac orci varius ullamcorper. Duis tincidunt viverra tincidunt. Fusce dignissim a nisl a tempus. In imperdiet elementum sem, eu faucibus enim pretium in. Suspendisse a lobortis nibh. Aliquam magna nibh, malesuada sed ligula eget, sollicitudin posuere velit. Integer hendrerit est a efficitur blandit.
                </p>
              </div> 
            </div>
          </div>
        </div>

        <div className={styles.section}>
          <h2 className={styles.sectionTitle}>Get in touch</h2>
          <div className={styles.sectionContent}>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris imperdiet sem ac orci varius ullamcorper. Duis tincidunt viverra tincidunt. Fusce dignissim a nisl a tempus. In imperdiet elementum sem, eu faucibus enim pretium in. Suspendisse a lobortis nibh. Aliquam magna nibh, malesuada sed ligula eget, sollicitudin posuere velit. Integer hendrerit est a efficitur blandit.
            </p>
          </div>
        </div>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
