import Head from 'next/head'
import Image from 'next/image'
import IntroMenu from '../components/introMenu'
import styles from '../styles/PaymentPage.module.css'
import { RxCross2 } from 'react-icons/rx'
import { IconContext } from 'react-icons'
import { useState, useContext, useEffect } from 'react'
import { ThreeDots } from 'react-loader-spinner'
import { useRouter } from 'next/router'

export default function PaymentPage({ setCart }: any) {
  const router = useRouter()
  const { total } = router.query;

  useEffect(() => {
    setCart([])
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <IntroMenu />

        <div className={styles.section}>
          <h1 className={styles.title}>Payment</h1>
          <p className={styles.text}>Please pay ${total} via PayNow to 85880918, or by scanning the QR code below. Indicate your name in the payment reference</p>
          <Image src="/images/test-qr.jpg" alt='paynow' width={400} height={400} className={styles.qr} />
          <p className={styles.text}>Thank you for your purchase! I hope you have a nice day :)</p>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
