import Head from 'next/head'
import Image from 'next/image'
import IntroMenu from '../components/introMenu'
import styles from '../styles/ProductPage.module.css'
import { useRouter } from 'next/router'
import { useState, useContext, useEffect } from 'react'
import { CartContext } from '../CartContext';


export default function ProductPage({ productDetails, cart, setCart }: any) {
  const router = useRouter()
  const productData: any = router.query
  const [quantity, setQuantity] = useState(0);
  const [hasAddedToCart, setHasAddedToCart] = useState(false);
  
  useEffect(() => {
    setQuantity(0);
  }, []);

  const addToCart = () => {
    if (quantity <= 0) {
      return;
    }
    const existingIndex = cart.map((elem: any) => elem.productId).indexOf(productData._id)
    if (existingIndex >= 0) {
      // product already exists in cart
      const newCart = [...cart]
      newCart[existingIndex].quantity = newCart[existingIndex].quantity + quantity
      setCart([...newCart])
    } else {
      setCart([...cart, { productId: productData._id, quantity }])
    }

    setHasAddedToCart(true)
  }


  // console.log('product page');
  // console.log(cart);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <IntroMenu />

        <div className={styles.section}>
          <Image className={styles.image} src={productData.picLink} alt="Product image" width={500} height={500}></Image>
          <div className={styles.productInfo}>
            <h1 className={styles.productTitle}>{productData.name}</h1>
            <h2 className={styles.price}>${productData.price}</h2>
            <p>{productData.details}</p>
            <div className={styles.productQuantity}>
              <p>Quantity</p>
              <input className={styles.quantitySelector} type="number" value={quantity} onChange={(e) => setQuantity(Math.max(parseInt(e.target.value), 0))} />
            </div>
            <button className={styles.addToCart} onClick={addToCart} disabled={hasAddedToCart}>{hasAddedToCart ? "Added!" : "Add to cart"}</button>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
